name: Documentation Issue
description: Report an issue with documentation
title: "[DOCS]: "
labels: ["documentation"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve our documentation! Please fill out the sections below.
  
  - type: dropdown
    id: doc-type
    attributes:
      label: Documentation Type
      description: What type of documentation issue is this?
      options:
        - README.md
        - Function help/comments
        - Code examples
        - Installation instructions
        - Other
    validations:
      required: true
  
  - type: textarea
    id: issue
    attributes:
      label: Issue Description
      description: Describe the documentation issue you found
      placeholder: What's wrong with the current documentation?
    validations:
      required: true
  
  - type: textarea
    id: location
    attributes:
      label: Location
      description: Where is this documentation located?
      placeholder: |
        - File: (e.g., README.md, Public/Import-GlookoCSV.ps1)
        - Section: (e.g., "Installation", "Usage Examples")
        - Line number (if applicable): 
    validations:
      required: true
  
  - type: textarea
    id: suggestion
    attributes:
      label: Suggested Improvement
      description: How do you think this should be improved?
      placeholder: Describe what should be changed or added...
    validations:
      required: false
  
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the documentation issue here.
      placeholder: Any additional information...
    validations:
      required: false
